name: Build
on: [push]
jobs:
  style:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Name
        run: whoami

